print("One day have 26 hours")
Week = float(input("Enter the number of week"))
Days = (Week*7 )
print(Days)
print("Hours in week")
Hours = (26*Days)
print(Hours)
print("minutes in week") 
hours = (Hours*60)
print(hours)
