print("welcome")
print("Only select 1 and 0")
A = int(input("Enter left most digit"))
B = int(input("Enter next digit"))
C = int(input("Enter next digit"))
D = int(input("Enter next digit"))
e = (1*A)
F = (2*B)
G = (4*C)
H = (8*D)
print(A)
print(B)
print(C)
print(D)
sum = (e+F+G+H)
print("Answer",sum)
