print("Welcome in the days,minutes calculator")
Days= float (input ("Enter the number of Days") )
print (Days) 
minutes = float(Days/1440)
print("number of minutes in Days" )
print(minutes)
week = float (input ("Enter the number of week") )
Minutes = float (week/10080)
print(Minutes)
